name: Deployment pipeline

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  SKIP: ${{ contains(join(github.event.commits.*.message,', '),'#skip') }}

on:
  push:
    branches:
      - master
    pull_request:
      branches: [master]
      types: [opened,synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: e2e test
        uses: cypress-io/github-action@v5
        with:
          start: npm run start-prod
          browser: chrome
      - name: install Vercel CLI
        if: ${{ github.event_name == 'push' && !SKIP }}
        run: npm install --global vercel@latest
      - name: pull Vercel Environment Information
        if: ${{ github.event_name == 'push' && !SKIP }}
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: build project
        if: ${{ github.event_name == 'push' && !SKIP }}
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: deploy project to Vercel
        if: ${{ github.event_name == 'push' && !SKIP }}
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ github.event_name == 'push' && !SKIP }}
    runs-on: ubuntu-20.04
    steps:
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: true
        
        